# Global defaults
threads: 8
bin_size: 1
output_dir: test_data/test_oe/results
# Set to the annotation GTF you want featureCounts to use
gtf: test_data/test_oe/test.gtf

# Samples block. Add entries per sample with method, barcodes and bam path.
# - method: ritSeq (single barcode) or oeSeq (dual barcode)
# - forward_barcode / reverse_barcode: barcode sequences in forward orientation
# - merge_forward_reverse: only used for ritSeq (True to merge F and R into F_plus_R)
#   as the same barcode is given in F and RC orientation
samples:
  TbRIT-8166:
    bam: test_data/test_oe/test_region.bam
    method: oeSeq
    forward_barcode: GATAGAGTGGTACCGGCCGG
    reverse_barcode: CAATGATAGAGTGGCCGGCC
